/* Damark service-page content (verbatim from approved website copy).
   Consumed by ServiceDetailScreen.jsx and listed on ServicesScreen.jsx. */
window.DAMARK_SERVICES = [
  {
    slug: 'cnc-precision-machining',
    nav: 'CNC Precision Machining',
    card: 'High-tolerance milling, turning, and production runs — including horizontal machining centers with pallet changers.',
    img: 'precision-machining.jpg',
    h1: 'CNC Precision Machining: Small Batch to Production Runs',
    eyebrow: 'CNC Machining',
    introTitle: 'Precision Machining Built on Thirty Years of Floor Experience',
    intro: [
      "CNC machining at Damark isn't just about having the equipment. It's about knowing how to run it. Our experienced team has the background to look at a print, identify what's going to cause problems before the first cut, and machine the part right the first time.",
      "We handle jobs other shops pass on: tight tolerances, difficult materials, low quantities, and parts with no room for error. And when a job becomes repeat work, our documented processes make sure the tenth order runs the same as the first.",
    ],
    whatTitle: 'What Our CNC Machining Service Covers',
    what: [
      ['CNC Milling', 'Multi-axis milling including 4th-axis capability up to 22 inches. Prismatic parts, complex geometries, and tight-tolerance work across a range of sizes. Our horizontal machining centers run with pallet changers, keeping production moving on repeat work.'],
      ['CNC Turning / Lathe Work', 'Precision turned parts across a range of diameters and lengths. We run both CNC lathes and manual lathes for secondary operations, giving us flexibility other shops don\u2019t have.'],
      ['Small Batch & Job Shop Work', 'One part or fifty. We quote it. Most high-volume shops won\u2019t touch small runs because they can\u2019t make the economics work. We can, and we do. Regularly.'],
      ['Production Runs', 'For repeat work we build documented routings, setup sheets, and in-process inspection checkpoints. We incorporate bill of materials into our routings so material is ordered correctly and on time.'],
    ],
    whoTitle: 'Who We Work With',
    who: [
      'OEM manufacturers who need a reliable outside supplier for production components',
      'Other machine shops who need overflow capacity or specialty work they can\u2019t run in-house',
      'Equipment designers and builders who need machined components for custom machinery',
      'Engineers and purchasing managers who need a shop they can trust to hold tolerance and meet deadlines',
      'Independent inventors and product developers who need a capable shop for one-off and early-production work',
    ],
    processTitle: 'What to Expect When You Work With Us',
    process: [
      ['Send us your print or describe the job', 'Send your RFQ from the form or call us directly. No formal print yet? We can work from sketches, samples, or a description.'],
      ['We review and quote', 'We look at the print carefully \u2014 not just for what it says, but for what might cause issues in machining. If we see something that\u2019s going to cost you time or money, we say so before we quote.'],
      ['First article and approval', 'For new work we typically start with a first article: one part made to print, inspected, and approved before we proceed.'],
      ['Production and documentation', 'Once the process is established, it\u2019s documented. Every repeat order runs off the same setup sheets, tooling documentation, and inspection checkpoints.'],
      ['Delivery', 'Parts ship on your account or we arrange delivery depending on the job. We can also coordinate plating, heat treating, and other outside processes on your behalf.'],
    ],
    whyTitle: 'Why Shops and Manufacturers Keep Sending Us Work',
    why: [
      "Damark has built most of its business from customers who found us through someone who used to work somewhere else \u2014 an engineer who moved companies, a production manager who switched industries. They bring us with them because the work was right and the relationship was straight.",
      "We\u2019ve machined components that ended up in agricultural equipment, military lighting systems, aerospace applications, nuclear facilities, and construction machinery. We\u2019ve also made a $400 job for a guy who needed three pieces and couldn\u2019t find anyone else to touch it. We treat both the same way.",
    ],
    quote: ['We build farm equipment parts up to aerospace. Ground to sky. That\u2019s really the gist of it.', 'Dave Buerger', 'Founder'],
    faq: [
      ['What materials can Damark machine?', 'We work across a wide range of materials including aluminum, carbon steel, stainless steel, tool steel, hardened steels, plastics, castings, and forgings. If you have a specific material in mind, contact us and we\u2019ll confirm whether it\u2019s something we can run.'],
      ['What is your minimum order quantity?', 'There is no minimum. We regularly run one-piece jobs and small batches that larger production shops won\u2019t quote. If you need it made, send it over and we\u2019ll give you a number.'],
      ['Do you hold tight tolerances?', 'Yes. Tight-tolerance work is a significant part of what we do. We have calibrated inspection equipment on the floor, including optical comparator measurement, and our machinists perform in-process checks throughout the job.'],
      ['Are you ISO certified?', 'We are ISO compliant. Our quality system includes documented in-process routings, machine setup sheets, calibrated gauges, and first sample inspection reports. We regularly supply parts to ISO-certified customers who require documentation from their outside suppliers.'],
      ['Can you handle repeat production orders?', 'Yes. For repeat work we build documented routings and incorporate bill of materials into our ordering process so material is ready when the job kicks off. Several of our customers have been placing repeat orders with us for years.'],
      ['Do you work with other machine shops?', 'Yes, and we do it regularly. If you have overflow work, a job outside your core capability, or a customer order you can\u2019t fit in your schedule, we can help. We protect your customer relationships.'],
      ['What is your typical lead time?', 'Lead time depends on the job: material availability, complexity, and current shop capacity. Contact us with your details and deadline and we\u2019ll give you a straight answer on whether we can meet it.'],
      ['Can you coordinate outside processes like plating or heat treating?', 'Yes. We regularly coordinate outside processing on behalf of our customers. You don\u2019t have to manage multiple vendors if you don\u2019t want to.'],
    ],
  },
  {
    slug: 'fixturing-tooling',
    nav: 'Fixturing & Tooling',
    card: 'Weld fixtures, machining fixtures, robotic tooling, and hydraulic clamping. Designed in-house in SolidWorks.',
    img: 'tooling-fabrication-banner.png',
    h1: 'Weld Fixtures, Machining Fixtures & Custom Tooling',
    eyebrow: 'Fixturing & Tooling',
    introTitle: 'Fixtures That Work the First Time, Because We Design and Build Them',
    intro: [
      "A fixture is only as good as the engineering behind it. At Damark, design and fabrication happen in the same building, by the same team. When the person designing your fixture can walk over and talk to the person building it \u2014 and prove it out on the floor before it ships \u2014 you end up with tooling that actually does what it\u2019s supposed to do.",
      "Damark has designed and built hundreds of fixtures over the last few decades. That depth of experience is in every fixture that leaves this shop.",
    ],
    whatTitle: 'What We Design and Build',
    what: [
      ['Weld Fixtures', 'Custom weld fixtures for manual, semi-automated, and robotic welding operations. We design to your weldment geometry, clamping sequence, and production environment. Repeatability is built in from the start.'],
      ['Machining Fixtures', 'Fixtures for CNC milling and turning operations: locating, clamping, and holding parts in the right position, every time. We design for rigidity, chip clearance, and operator usability.'],
      ['Robotic Tooling', 'End-of-arm tooling and robotic work cell fixtures designed around your robot and your part geometry.'],
      ['Hydraulic & Pneumatic Clamping', 'Fixtures with integrated hydraulic or pneumatic clamping for faster cycle times and more consistent clamping force. Useful where operator variation is a problem.'],
      ['Sensing & Monitoring Integration', 'Fixtures with part-presence sensing, clamping confirmation, or in-process monitoring built in. We work with your controls team or handle the integration ourselves.'],
      ['Amada & Brake Tooling', 'Custom and modified tooling for press brake and punch press operations, including Amada-compatible tooling.'],
    ],
    whoTitle: 'Who We Work With',
    who: [
      'Engineers and production managers running automated or semi-automated assembly and welding lines',
      'Machine shops that need work holding for a specific CNC operation',
      'Equipment designers and builders who need tooling designed alongside custom machinery',
      'Job shops who need a capable outside source for fixture design and build',
    ],
    processTitle: 'How the Process Works',
    process: [
      ['You describe what you need', 'Send us part prints, weldment drawings, or assembly documents. If you have an existing fixture that isn\u2019t working right, send that too. A description of the problem is often as useful as a drawing of the solution.'],
      ['We design it in SolidWorks', 'Our engineers model the fixture in full 3D, working through clamping sequence, locating strategy, and operator access. You review the design before we cut metal.'],
      ['We build and prove it out', 'The fixture is built in-house on the same floor as our machining and welding operations. We prove it out with your part geometry before it ships.'],
      ['We deliver a fixture that works', 'And if something comes up after delivery \u2014 a design change, a worn component, a modification \u2014 we\u2019re the same shop that built it. Call us.'],
    ],
    whyTitle: 'Why This Work Belongs at Damark',
    why: [
      "Most shops either design fixtures or build them. We do both, which means the engineer who designs your fixture answers to the same standard as the machinist who builds it. There\u2019s no gap between what was designed and what gets made.",
      "We\u2019ve built fixtures that load parts automatically, clamp with hydraulic force, confirm part presence with sensors, and integrate directly into robotic work cells. We\u2019ve also built simple manual weld fixtures for small shops doing low-volume work. The level of sophistication depends on what the job calls for.",
    ],
    quote: ['We\u2019ve built hundreds of fixtures. Everything from a simple weld fixture to a full robotic work cell setup.', 'Dave Buerger', 'Founder'],
    faq: [
      ['Do you offer design-only services, or do you have to build the fixture too?', 'We can do design-only if that\u2019s what you need \u2014 a fully detailed SolidWorks model and drawing package your team or another shop can build from. That said, most customers find it cleaner to have design and build under one roof.'],
      ['What information do I need to provide to get started?', 'At minimum, the part print and a description of the operation. It helps to know your production volume, clamping preferences, and any equipment constraints. If you have an existing fixture or a sketch, send that too.'],
      ['Can you modify an existing fixture?', 'Yes. If you have a fixture that\u2019s not quite working right \u2014 wrong clamp location, worn locators, a design that didn\u2019t account for a part change \u2014 we can evaluate it and make modifications. We\u2019ll tell you whether a fix or a redesign makes more sense.'],
      ['Do your fixtures include sensing and part-present detection?', 'Yes, when the application calls for it. We can integrate pneumatic, proximity, or other sensing. If you have a preferred sensor or controls interface, let us know upfront and we\u2019ll design to it.'],
      ['What lead time should I expect?', 'It depends on fixture complexity, design time, and current shop capacity. Simple fixtures move quickly; complex tooling with hydraulic clamping or sensing takes longer. Contact us with your application and deadline.'],
      ['What is the fixture made from?', 'Most fixtures are built from mild steel or tool steel depending on the application. We can use aluminum for lighter-duty or weight-sensitive applications. Material selection is part of the design conversation.'],
    ],
  },
  {
    slug: 'prototyping',
    nav: 'Prototyping',
    card: 'Got an idea on paper or in your head? We help you get it made, tested, and refined before production.',
    img: 'trak-dpm5.jpg',
    h1: 'Prototype Parts Made Right, From Sketch to Finished Piece',
    eyebrow: 'Prototyping',
    introTitle: 'From an Idea to a Part You Can Hold in Your Hand',
    intro: [
      "Most prototype shops want a complete print before they\u2019ll quote anything. We\u2019re not that kind of shop. If you have a sketch on paper, a part you want to copy, or an idea you\u2019ve been sitting on and haven\u2019t been able to get made \u2014 bring it to us. We\u2019ll work through it with you.",
      "Prototyping at Damark means you get engineering judgment alongside the machining. If what you\u2019ve drawn isn\u2019t going to work the way you expect, we\u2019ll tell you before we make chips, not after.",
    ],
    whatTitle: 'What Prototyping at Damark Covers',
    what: [
      ['First-Off Parts', 'The first physical version of something that hasn\u2019t been made before. We machine it from your print, sketch, or model, and give you a part you can test, measure, and evaluate.'],
      ['Iterative Development', 'When the first version isn\u2019t quite right, we iterate. Some prototypes take one pass, some take three. We work through it without treating each revision like a separate project from scratch.'],
      ['Design-to-Print Work', 'If you don\u2019t have a formal print, we can help develop one. We model in SolidWorks and can produce a drawing package from a physical sample, a sketch, or a description.'],
      ['Sample Parts for Customer Approval', 'Need a physical sample to show a customer or get sign-off before production? We make those. One part, made right, documented if needed.'],
      ['Form, Fit & Function Models', 'When you need to know if a part fits in the assembly, clears an obstruction, or interfaces correctly with a mating component, before you commit to production quantities.'],
    ],
    whoTitle: 'Who We Work With',
    who: [
      'Independent inventors who need someone to actually build it, not just quote it with a 10-piece minimum',
      'Equipment designers and custom machinery builders proving out a design before the full build',
      'OEMs and small manufacturers entering a new product category who need a prototype first',
      'Engineers with a problem to solve: a replacement part that doesn\u2019t exist, a modification, or a one-off solution',
    ],
    processTitle: 'How Prototyping Works Here',
    process: [
      ['You tell us what you\u2019re trying to build', 'Print, sketch, part sample, or verbal description. Bring whatever you have. The more context about what the part needs to do, the better we can help.'],
      ['We give you honest feedback before we start', 'If we see something that\u2019s going to cause a problem in machining or in use, we say so. If there\u2019s a simpler way to get the same result, we point it out.'],
      ['We machine the first piece', 'Made to your print or agreed specification, and inspected before it leaves the shop.'],
      ['We revise if needed', 'If the first piece reveals something that needs to change, we make that change and go again. This is part of the process, not a problem.'],
      ['We document as you go', 'When you\u2019re ready to move toward production, the work we\u2019ve done on the prototype feeds directly into the production routing. You\u2019re not starting from scratch.'],
    ],
    whyTitle: 'Why Inventors and Engineers Come Back to Us',
    why: [
      "Prototyping customers tend to come back for one reason: they got honest feedback, the part was made right, and when it needed to change, the process wasn\u2019t painful.",
      "We\u2019ve made prototype parts for independent inventors working out of garages, for product designers at established manufacturers, and for engineers who needed a part made fast because something in the field was broken.",
    ],
    quote: ['There\u2019s a guy building a corn grinder. He\u2019s been here two or three times. Comes in with his sketch and we work through it with him.', 'Brock Buerger', 'Owner'],
    faq: [
      ['Do I need a complete print to get a prototype made?', 'No. We work from full SolidWorks models, PDF drawings, hand sketches, physical samples, and verbal descriptions. Lack of a formal print isn\u2019t a barrier to getting started. Contact us and tell us what you have.'],
      ['Can Damark help with the design, or just the machining?', 'Both. If you have an idea but not a design, we can model it in SolidWorks and work through it with you. We\u2019re not a pure design firm, but we\u2019re not going to machine something we can see is going to fail either.'],
      ['What if the first prototype isn\u2019t right and I need changes?', 'That\u2019s normal and expected. We iterate. We don\u2019t treat each revision as a brand-new job with a brand-new setup charge.'],
      ['How many prototypes can I order?', 'As many or as few as you need. One piece is fine. Three for testing and one for a customer presentation is fine too.'],
      ['What materials can you prototype in?', 'The same materials we production-machine: aluminum, steel, stainless, tool steel, plastics, and others. If the material you want isn\u2019t practical for a prototype, we can discuss functional equivalents.'],
      ['Can you take a prototype part into production?', 'Yes. The documentation from the prototype phase \u2014 inspection data, setup notes, tooling decisions \u2014 gives us a head start on the production routing. You\u2019re not starting from zero.'],
    ],
  },
  {
    slug: 'reverse-engineering',
    nav: 'Reverse Engineering',
    card: 'Part discontinued? We measure it, model it in SolidWorks, and manufacture a replacement.',
    img: 'equipment-doosan.jpg',
    h1: 'Reverse Engineering: When the Drawing Doesn\u2019t Exist',
    eyebrow: 'Reverse Engineering',
    introTitle: 'The Original Is Gone. The Machine Still Has to Run.',
    intro: [
      "Parts go out of production. Manufacturers shut down. Drawings get lost. Equipment that\u2019s been running for twenty years doesn\u2019t come with a parts catalog anymore. When that happens \u2014 and a line is down or a machine is sitting idle \u2014 you need someone who can look at a worn, broken, or damaged part and figure out what it was supposed to be.",
      "That\u2019s what we do. We measure it, model it in SolidWorks, produce a print, and machine a replacement. We apply engineering judgment, not just caliper-to-drawing copying. If the part is worn, we interpret the wear. If it\u2019s cracked, we figure out why it cracked.",
    ],
    whatTitle: 'What Reverse Engineering at Damark Covers',
    what: [
      ['Part Measurement & Documentation', 'We measure the physical part using precision inspection equipment, including 3D scanning. We document geometry, material characteristics, and surface finish or tolerance requirements.'],
      ['SolidWorks Modeling', 'We build a full 3D model in SolidWorks. This becomes the basis for the manufacturing drawing and the production routing for future orders.'],
      ['Manufacturing Drawing Production', 'A complete engineering drawing from the model: a real print, with tolerances, material callouts, and surface finish specs. You own that drawing.'],
      ['Replacement Part Manufacturing', 'We don\u2019t just document. The measurement, modeling, and manufacturing all happen at Damark.'],
      ['Engineering Analysis & Improvement', 'If the original failed because of a design weakness, we can discuss whether the replacement should be modified to perform better. The option is there.'],
    ],
    whoTitle: 'Who Needs This Service',
    who: [
      'Maintenance managers and plant engineers with legacy equipment no longer supported by the original manufacturer',
      'Equipment owners with machinery that predates modern CAD systems',
      'Manufacturers who need replacement components for production equipment no longer in current production',
      'Machine shops whose customers bring them worn or broken parts and need a single supplier from measurement to replacement',
    ],
    processTitle: 'How the Process Works',
    process: [
      ['You bring us the part', 'Ship it or drop it off. If it can\u2019t be removed from the equipment, we may be able to work from photographs and field measurements.'],
      ['We measure and evaluate it', 'Using precision measuring equipment and 3D scanning to capture the geometry. We also evaluate condition: what\u2019s worn, what\u2019s damaged, what the original dimensions likely were.'],
      ['We model it and produce a drawing', 'The model and drawing give us a repeatable manufacturing baseline. You get a copy of the drawing.'],
      ['We quote the replacement', 'We\u2019ll give you a price for the first piece and, if you want, a small stock quantity so you\u2019re not in the same situation six months from now.'],
      ['We machine and deliver', 'Made in-house, inspected before it ships.'],
    ],
    whyTitle: 'Engineering Judgment Is What Makes This Work',
    why: [
      "Reverse engineering isn\u2019t measurement. Anyone can measure a worn part and get the wrong answer. The worn surfaces aren\u2019t the original surfaces. The cracks tell you about the loads. The material hardness tells you something about what the original designer was solving for.",
      "We apply real engineering thinking to this process, not just a caliper and a model. That\u2019s the difference between a replacement part that fits and runs, and one that fails the same way the original did.",
    ],
    quote: ['The worn surfaces aren\u2019t the original surfaces. The cracks tell you about the loads. That\u2019s the difference between a replacement that runs and one that fails the same way.', 'Dave Buerger', 'Founder'],
    faq: [
      ['What condition does the part need to be in?', 'Worn, damaged, and partially broken parts are all workable in most cases. We evaluate when we receive it and tell you whether we have enough to work from. Even for destroyed parts, photographs, partial drawings, and context can be enough.'],
      ['Can you work from photographs or partial drawings instead of a physical sample?', 'Sometimes, depending on complexity. A simple turned part might be reconstructable from good photographs. More complex parts with tight tolerances really need to be in front of us. Send what you have and we\u2019ll tell you.'],
      ['Will you provide me with a drawing of the part?', 'Yes. The drawing is yours. We produce a full SolidWorks model and a manufacturing drawing, and you get copies of both.'],
      ['How do you handle parts that failed in service? Do you just copy the failure?', 'No. If a part failed because of a design issue, we flag it and discuss whether the replacement should match the original spec or be modified. Sometimes copying exactly is right. Sometimes it isn\u2019t.'],
      ['What is the typical turnaround?', 'It depends on complexity. We want to do it right, not fast. For many parts, a few weeks. Complex geometry or unusual materials may take longer.'],
      ['What if I need more than one replacement? Can you stock them?', 'Yes. Once the part is documented, ordering additional quantity is straightforward. We can quote a small stock quantity at the same time as the first piece.'],
    ],
  },
  {
    slug: 'fabrication-welding',
    nav: 'Fabrication & Welding',
    card: 'Structural fabrication, custom assemblies, weld fixtures, and repair work — all in-house.',
    img: 'welding.jpg',
    h1: 'In-House Fabrication & Welding',
    eyebrow: 'Fabrication & Welding',
    introTitle: 'Fabrication and Machining Under One Roof',
    intro: [
      "When fabricated components also require machined features, or when a weld fixture needs to be built to tight dimensional tolerances, having fabrication and machining in the same building matters. You don\u2019t coordinate between two vendors. You don\u2019t lose time in transit. The machinist and the welder work five feet apart.",
      "Damark has offered in-house fabrication and welding since the beginning. It\u2019s part of how we stay useful to customers who don\u2019t want to manage a supply chain to solve one problem.",
    ],
    whatTitle: 'What Our Fabrication and Welding Services Cover',
    what: [
      ['Custom Structural Fabrication', 'Frames, brackets, supports, enclosures, and structural components built to your drawings. We work from customer prints or develop the design in-house for simpler assemblies.'],
      ['Custom Weld Assemblies', 'From simple brackets to multi-component structures. If the weldment also requires machined surfaces, bores, or features, we handle that in-house without shipping it out.'],
      ['Weld Fixture Fabrication', 'Fixtures for your welding operations, designed and built to hold your parts in position during the weld cycle.'],
      ['Fabrication Repair & Modification', 'Existing assemblies that are worn, cracked, broken, or need modification for a new application. We evaluate, repair or rebuild, and return it ready to use.'],
      ['Form Die, Stamp Die & Fixture Repair', 'Repair and reconditioning of forming, stamping, and fixture tooling that has worn or been damaged in service.'],
      ['Sawing & Material Prep', 'We have a CNC saw for material cutting and prep. If a job needs stock cut to length before it goes to the mill or weld table, that happens in-house.'],
    ],
    whoTitle: 'Who We Work With',
    who: [
      'Manufacturers who need custom fabricated components or weld assemblies as part of their product or equipment',
      'Machine builders and equipment designers who need fabricated structures machined to tolerance',
      'Maintenance and facilities teams who need repair or modification work on existing fabricated equipment',
      'Other machine shops who need fabrication capability they don\u2019t have in-house',
    ],
    processTitle: 'The Machining Changes Everything',
    process: [
      ['One roof, one team', 'At Damark, the machinist can walk over and talk to the welder before the first weld is laid. Fixturing for the weld is designed with the machining requirements in mind.'],
      ['Sequence planned from the start', 'The sequence is planned up front, not discovered after the fact. That\u2019s the difference between a part that shows up ready to use and one that requires rework at every handoff.'],
    ],
    whyTitle: 'Why This Work Belongs at Damark',
    why: [
      "Fabricated parts that require machined features are a coordination problem if your fab shop and machine shop are two different places. The assembly gets built, ships to the machine shop, the machine shop finds the weldment is out of tolerance, and now you\u2019re back at the fab shop for correction.",
      "At Damark, that gap doesn\u2019t exist. It\u2019s not a small thing.",
    ],
    quote: ['We started in fabrication and repair. That\u2019s the foundation everything else was built on.', 'Dave Buerger', 'Founder'],
    faq: [
      ['What materials do you weld?', 'We weld mild steel, stainless steel, and aluminum. If you have a specific material requirement, let us know upfront.'],
      ['Do you handle structural welding for load-bearing applications?', 'Contact us with your application. We can discuss what the weldment needs to do and whether our capability and process documentation meet your requirements.'],
      ['Can you fabricate from my drawings, or do you need to design the assembly?', 'Both. We regularly fabricate from customer-supplied drawings. For simpler assemblies, we can develop a design in-house, particularly when the assembly will have machined features.'],
      ['Do you offer repair work on existing fabricated assemblies?', 'Yes. Bring in the assembly or describe what\u2019s wrong. In many cases a worn or cracked assembly can be repaired and reconditioned for significantly less than building new.'],
      ['Can you handle the machining on a welded assembly without me finding a separate machine shop?', 'Yes \u2014 that\u2019s specifically one of the things we do well. Welded assemblies that require machined bores, faced surfaces, drilled patterns, or other features are handled in-house start to finish.'],
    ],
  },
  {
    slug: 'shop-to-shop',
    nav: 'Outsourced Machining for Shops',
    card: 'Overflow, specialty, and hard-to-fit machining for other shops. We protect your customer relationships.',
    img: 'doosan-dnm400.jpg',
    h1: 'Overflow & Specialty Work for Other Shops',
    eyebrow: 'Shop-to-Shop Services',
    introTitle: 'A Shop You Can Send Work To',
    intro: [
      "A meaningful share of what runs through Damark\u2019s floor comes from other shops. Overflow jobs. Work that\u2019s outside a shop\u2019s core capability. Orders a customer pushed in with a deadline that won\u2019t fit the schedule. Parts that need a process \u2014 4th-axis, HMC, tight-tolerance inspection \u2014 that the sending shop doesn\u2019t have.",
      "We do this work regularly. We\u2019ve been doing it for years. Your customer doesn\u2019t hear from us. Your relationship stays yours.",
    ],
    whatTitle: 'The Work We Take From Other Shops',
    what: [
      ['Overflow & Capacity Work', 'We run the overflow while your shop stays focused on what\u2019s already committed. No minimum lot size, no minimum relationship requirement.'],
      ['Specialty Operations', '4th-axis milling, HMC work with pallet changers, tight-tolerance turned parts, optical comparator inspection, or SolidWorks-supported programming for complex geometry.'],
      ['Hard-to-Machine Materials', 'Hardened steels, stainless, or difficult castings, where the risk is high enough that you\u2019d rather send it out than tie up your own equipment.'],
      ['Tight-Tolerance Jobs', 'Parts that require documented inspection \u2014 first sample inspection reports, in-process measurement, calibrated gauges \u2014 that your shop\u2019s documentation system doesn\u2019t support.'],
      ['Short-Run & One-Off Work', 'One or two pieces, not worth a setup on your floor, but important enough to your customer relationship that you need them done right.'],
      ['Fixture & Tooling Work', 'If you need a weld fixture, machining fixture, or custom tooling built for your own shop, we can handle that too.'],
    ],
    whoTitle: 'What Kind of Shops Send Us Work',
    who: [
      'General machine shops with more CNC milling and turning work than their floor can absorb',
      'Tool and die operations that need machined components outside their specialty',
      'Weld shops and fabricators whose customers need machined features they can\u2019t produce',
      'Manufacturers with in-house machining who have a job that doesn\u2019t fit their equipment or schedule',
      'Job shops who need a second-tier supplier they can trust on work they care about',
    ],
    processTitle: 'How We Protect Your Customer Relationships',
    process: [
      ['We don\u2019t call your customer', 'We don\u2019t put our name on the box. We don\u2019t pitch them on coming to us directly. You brought us the work. The relationship is yours.'],
      ['We sign your NDA', 'If you need a non-disclosure agreement before you send work over, that\u2019s not a problem. We\u2019ll sign it.'],
      ['We build long-term partnerships', 'The ones that last are built on the same thing every good business relationship is: the work gets done right, communication is straight, and nobody embarrasses the other party.'],
    ],
    whyTitle: 'Why Shops Come Back',
    why: [
      "The shops that send us work consistently do it because the parts come back right and the communication is straight. They know what\u2019s happening with their job. If something comes up, we call. We don\u2019t surface problems at delivery.",
      "We also have the equipment to back it up: a 15,000 sq ft facility, horizontal machining centers with pallet changers, 4th-axis milling, CNC lathes, in-house SolidWorks programming, and a calibrated inspection process.",
    ],
    quote: ['We do a lot of work for other shops. Overflow, stuff they can\u2019t do. It\u2019s a big part of what we run.', 'Brock Buerger', 'Owner'],
    faq: [
      ['How do you handle confidentiality? Will you contact my customer?', 'No. We work for you, not your customer. We don\u2019t reach out to anyone on the other end of your relationship. If you want a formal NDA in place before you send a print, we\u2019ll sign it.'],
      ['What types of jobs are the best fit?', 'Milling and turning across a wide range of metals and plastics, including 4th-axis, HMC production work, or tight-tolerance inspection documentation. Fixture and tooling work. Small batch and repeat production.'],
      ['Do you have a minimum order size or commitment?', 'No minimums. If you have a one-piece job that matters to your customer relationship, send it. We\u2019ll quote it.'],
      ['How do you handle communication on an active job?', 'You deal with the same people throughout. If something comes up \u2014 a question on the print, a material substitution, a lead time issue \u2014 we call you directly. We don\u2019t let things drift and surprise you at delivery.'],
      ['Can you support the documentation my customer requires?', 'Our processes are ISO compliant. We can provide in-process documentation, first sample inspection reports, and calibrated measurement data. Tell us the requirements before we quote and we\u2019ll confirm.'],
      ['What is your typical capacity situation?', 'Shop capacity varies. Contact us with your job and timeline. We\u2019d rather tell you we\u2019re full than take the work and miss your deadline.'],
    ],
  },
  {
    slug: 'emergency-support',
    nav: 'Emergency & After-Hours',
    card: 'Line down on a Saturday? Existing customers can reach us. Call us and you get a person.',
    img: 'iso-compliant.jpg',
    h1: 'After-Hours Support for Existing Customers',
    eyebrow: 'Emergency & After-Hours Support',
    introTitle: 'When Something Goes Wrong at 9 PM on a Friday',
    intro: [
      "Production problems don\u2019t happen at convenient times. A critical component fails. A part wears out and there\u2019s no spare. A line goes down and the morning shift can\u2019t start until something gets fixed.",
      "For existing Damark customers, you\u2019re not alone in that situation. Call us. We\u2019ll pick up or we\u2019ll call back. This isn\u2019t a 24/7 call center \u2014 it\u2019s a shop owned by people who understand what it means to have production stopped, and who\u2019ve built enough of a relationship to show up when it matters.",
    ],
    whatTitle: 'What After-Hours Support Looks Like',
    what: [
      ['Direct access, not a ticket system', 'If you\u2019re an existing customer and something goes wrong, you call Brock\u2019s cell. You talk to a person who knows your account and your equipment and can make a decision about what\u2019s possible.'],
      ['Parts we\u2019ve made before', 'If it\u2019s a part we\u2019ve made before and we have material on hand, we may be able to turn something around faster than normal.'],
      ['Parts we haven\u2019t made before', 'We\u2019ll talk through what we know and figure out the fastest path.'],
      ['When we genuinely can\u2019t help', 'We\u2019ll tell you that \u2014 and we might know who can. We don\u2019t make promises we can\u2019t keep. But we do pick up the phone.'],
    ],
    whoTitle: 'Who This Service Is For',
    who: [
      'Existing Damark customers \u2014 the shops, manufacturers, and production facilities we already have a working relationship with',
      'If you\u2019re not a current customer but you need help fast and think Damark might solve it, call anyway. We\u2019ll tell you if we can help.',
    ],
    processTitle: 'How to Reach Damark After Hours',
    process: [
      ['Existing customers', 'You should have Brock\u2019s direct number. Use it.'],
      ['Don\u2019t have it?', 'Call the main shop line at (920) 269-7825 and leave a detailed message: what the part is, what failed, what you need, and your callback number.'],
      ['Shop hours', 'Monday \u2013 Friday, 6:00 AM \u2013 2:30 PM. After-hours support is available for existing customers outside these hours.'],
    ],
    whyTitle: 'How It Works in the Real World',
    why: [
      "We\u2019re a small shop, which means the person who runs it is the person who picks up. That\u2019s not a policy. It\u2019s a disposition.",
    ],
    quote: ['Somebody needed a pin, some kind of carnival ride thing. They called us on a weekend, we got it done. That\u2019s just what you do.', 'Brock Buerger', 'Owner'],
    faq: [
      ['Is after-hours support available to new customers?', 'It\u2019s primarily set up for existing customers with established relationships. That said, if you\u2019re in a genuine emergency and you reach us, we\u2019ll hear you out. We won\u2019t hang up on someone because they\u2019re not already in the system.'],
      ['What types of emergencies can Damark help with?', 'Failed production components, broken fixtures, worn parts that need a quick replacement, critical tooling that needs repair or remaking. If the part can be machined or fabricated and we have material on hand, there\u2019s a real chance we can help.'],
      ['What response time should I expect after hours?', 'There\u2019s no guaranteed response window. This is a small shop, not a staffed help desk. In practice, if Brock is reachable, you\u2019ll hear back within the hour. Leave a clear message with your number and the nature of the problem.'],
      ['Does Damark charge a premium for emergency work?', 'Rush work often carries a premium \u2014 material sourcing, overtime, prioritizing your job over the queue. We\u2019ll be straight with you about what it takes. We\u2019re not going to gouge someone in an emergency, but we\u2019re not going to absorb real costs without acknowledging them.'],
      ['What if my emergency is something Damark can\u2019t handle?', 'We\u2019ll tell you that. And if we know a shop that can help, we\u2019ll say so. Getting you pointed in the right direction is worth something even when we\u2019re not the answer.'],
    ],
  },
];
